"use client";

import { useEffect } from "react";
// import Login from "@/app/login/page";
import { useRouter } from "next/navigation";

/*
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
*/

const Home = () => {
  const router = useRouter();
  useEffect(() => {
    router.push("/login");
  });
  return null;
};

export default Home;
