import React from "react";
import Login from "@/app/login/login";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const LoginPage = () => {
  return <Login />;
};

export default LoginPage;
